# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-14 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('starts_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_on', models.DateTimeField()),
                ('featured_image', models.ImageField(upload_to='featured image')),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
    ]
