# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-14 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='auction_description',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctions',
            name='auction_image',
            field=models.ImageField(default='hi', upload_to='auction image'),
            preserve_default=False,
        ),
    ]
